### ISSUE TITLE
require script caching when script 302-redirects to self with header("Location: ...") function

### ISSUE THREAD

**Issue by alex9216** [clagiordano/weblibs-configmanager#2]
Hello!
Suppose we are in save controller php script that saves some data to config file, and suppose that script 302-redirects to get method of that controller which retrieve written to that config-file data.
In that case php may cache require'd file and you get old data. To fix that, don't require config file, you may, for example, file_get_content's it and than eval returned string with config file.

**Comment by clagiordano** [comment]
Hello @alex9216, 
thanks for your point, I guess that could be caused by php opcache extension that caches already required files, but it is also used as very good caching strategy by this package to avoid continuously reload from disk of the same config file at every call.

Actually we use require keyword because the php config files has a return statement inside, so change it to php_file_get_contents isn't a drop in replacement and cause a breaking changes and force all people already using this package to change their own config files if they want to upgrade.

Of course it can be avoided as suggested using eval function but its use is discouraged because it is very dangerous and allow execution of arbitrary code and in some environment calling that function may be disabled for security reason.

Please see this page for more details:
https://www.php.net/manual/en/function.eval.php

Anyway you may consider to extend and override some functions to implement your desidered behavior but pay attention to the security issue that may caused by allowing users to write their own setting that may break your system.

**Comment by alex9216** [comment]
Yes. It works to with opcache_reset() or opcache_invalidate($script). You can add, for example, opcache_invalidate($configFilePath) at the end of [saveConfigFile](https://github.com/clagiordano/weblibs-configmanager/blob/0acd68e5df6ac480dc94c4c498c04f300630e86c/src/ConfigManager.php#L57) method (with check if function opcache_invalidate exists).

**Comment by clagiordano** [comment]
> Yes. It works to with opcache_reset() or opcache_invalidate($script). You can add, for example, opcache_invalidate($configFilePath) at the end of [saveConfigFile](https://github.com/clagiordano/weblibs-configmanager/blob/0acd68e5df6ac480dc94c4c498c04f300630e86c/src/ConfigManager.php#L57) method (with check if function opcache_invalidate exists).

Yes, this solution is very good, good work!
Applied this proposed solution, this is now available from v1.1.0.

Thanks.
